--=================== DataBase 01/09/2014 ==================
DROP TABLE ATMACT;
CREATE TABLE "ATMACT" ("CCS_OPERATE_DATE" DATE NOT NULL, "ATM_NO" VARCHAR(16) NOT NULL, "ATM_SEQNO" CHAR(8) NOT NULL, "TRANS_MESSAGE_CODE" VARCHAR2(4) NOT NULL, "SERVICE_TYPE" VARCHAR2(4), "TRANS_CODE" NUMBER(2), "FROM_ACC_CODE" NUMBER(2), "TO_ACC_CODE" NUMBER(2), "ATMCARD_LENGTH" NUMBER(2), "ATMCARD_ID" VARCHAR2(19), "PIN_BLOCK" VARCHAR2(32), "ATM_LOCATION" VARCHAR2(30), "ATM_OWNER" VARCHAR2(3), "ATM_CITY" VARCHAR2(3), "TRACE_NUMBER" NUMBER(6), COOP_FIID VARCHAR2(10), MEMBER_ID NUMBER(10), MEMBER_ACC NUMBER(10), COOP_BANK_ACC NUMBER(10), MEMBER_BANK_ACC NUMBER(10), COOP_REF VARCHAR(50), ITEM_AMT NUMBER(15,2) DEFAULT 0, FEE NUMBER(15,2) DEFAULT 0, LEDGER_BAL NUMBER(15,2) DEFAULT 0, AVAILABLE_BAL NUMBER(15,2) DEFAULT 0, RESPONSE_CODE CHAR(2), REVERSAL_CODE CHAR(2), APPROVE_CODE VARCHAR2(6), RESPONSE_MSG VARCHAR2(18), "OPERATE_DATE" DATE DEFAULT SYSDATE );
ALTER TABLE "ATMACT" ADD ( CONSTRAINT "PK_ATMACT" PRIMARY KEY ( "CCS_OPERATE_DATE", "ATM_NO", "ATM_SEQNO","TRANS_MESSAGE_CODE", "OPERATE_DATE", "TRANS_MESSAGE_CODE" )) ;

DROP TABLE "ATMTRANSACTION";
CREATE TABLE "ATMTRANSACTION" ("MEMBER_NO" CHAR(8) NOT NULL, "COOP_ID" CHAR(4) NOT NULL, "CCS_OPERATE_DATE" DATE NOT NULL, "OPERATE_DATE" DATE NOT NULL, "SYSTEM_CODE" CHAR(2) NOT NULL, "OPERATE_CODE" CHAR(3) NOT NULL, "ITEM_AMT" NUMBER(15,2) NOT NULL, "BANK_CODE" CHAR(3) NOT NULL, "BRANCH_CODE" CHAR(3) NOT NULL, "ATM_NO" VARCHAR2(12) NOT NULL, "ATM_SEQNO" VARCHAR2(8) NOT NULL, "ITEM_STATUS" NUMBER(1,0) DEFAULT 0 NOT NULL, "POST_STATUS" NUMBER(1,0) DEFAULT 0 NOT NULL, "POST_DATE" DATE, "SAVING_ACC" CHAR(15) NOT NULL, "EXPORT_STATUS" NUMBER(1,0) DEFAULT 0 , "EXPORT_DATE" DATE, "RECONCILE_DATE" DATE, "TRANS_CODE" VARCHAR2(4), "SMS_STATUS" NUMBER(1,0) DEFAULT 0, "SMS_DATE" DATE, "EMAIL_STATUS" NUMBER(1,0) DEFAULT 0, "EMAIL_DATE" DATE, "SEQ_NO" NUMBER(8,0)) ;
ALTER TABLE "ATMTRANSACTION" ADD ( CONSTRAINT "PK_ATMTRANSACTION" PRIMARY KEY ( "MEMBER_NO", "COOP_ID", "CCS_OPERATE_DATE" )) ;

--ไม่ต้องใช้ ATMCATD_ID เพราะมีผูกไว้ทั้งหมดอยู่แล้ว
--ALTER TABLE DPDEPTMASTER ADD ATMCARD_ID VARCHAR2(15);

--Flag เงินฝากที่ผู้กับ ATM
ALTER TABLE DPDEPTMASTER ADD ATMFLAG NUMBER(1) DEFAULT 0;

